### PR TITLE
Updating torch.range to torch.arange

### PR DESCRIPTION
**Pull request by jorshi**
[`torch.range` is now deprecated](https://pytorch.org/docs/stable/generated/torch.range.html) and should be replaced with `torch.arange`, which is consistent with pythons built-in range. `torch.range` also was producing errors with high-valued ranges, see #377

Merge #380 into this first.

### CODE REVIEW

**Comment by turian** [comment]
Yeah but what about older versions of pytorch? Do we break them? We should run a full jenkins

**Comment by turian** [comment]
Since when is it deprecated? Do you have a link?

**Comment by jorshi** [comment]
@turian `torch.range` has been deprecated in favour of `torch.arange` since torch v0.1 https://github.com/pytorch/pytorch/releases/tag/v0.1.12 -- so we should be good for backward compatibility :)

**Comment by turian** [comment]
Okay. Why are tests still breaking?

**Comment by jorshi** [comment]
Tests were breaking because the deprecated function call `Trainer.test(test_dataloader=)` was removed from Lightning (formally PTL) in [version 1.6](https://github.com/Lightning-AI/lightning/releases/tag/1.6.0), see https://github.com/Lightning-AI/lightning/pull/10325. `test_dataloader` was deprecated in [v1.4.0](https://github.com/Lightning-AI/lightning/releases/tag/1.4.0), see https://github.com/Lightning-AI/lightning/pull/7431. Replacing `Trainer.test(test_dataloader=)` with `Trainer.test(dataloader=)` will work for ptl>=1.4

**Pull request merged**
